version: '3'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:3000"
    volumes:
      - ".:/var/www/app"
      - /var/www/app/node_modules
  db:
    image: mongo:3.4
    expose:
      - "27017"
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata: